export default {
  cartStore: {
    pantries: {
      pantries: {
        result: [
          {
            pantry_id: 1,
            name: "The River Food Pantry",
            address: "2201 Darwin Rd",
            zip: 53704,
            city: "Madison",
            state: "WI",
            phone_number: "6084428815",
            details: "Here to serve! - Andy does not have a message~~",
            img_src:
              "https://lh5.googleusercontent.com/p/AF1QipM6UYI64xgIkJx1w_t7RLh8eVCjelB9ogeoW_A3=w426-h240-k-no",
            lat: 43.07,
            lon: -89.4,
            website: "https://www.riverfoodpantry.org/",
            reservations: [
              {
                reservation_id: 1,
                username: "sean1",
                order_time: "2021-03-25T21:03:39.000Z",
                estimated_pick_up: "2021-03-30T15:00:00.000Z",
                picked_up_time: "2021-04-09T12:02:52.000Z",
                approved: 1,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 1,
                    res_food_name: "Apple",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 3,
                    res_food_name: "Avocado",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 107,
                username: "sean1",
                order_time: "2021-03-25T21:04:11.000Z",
                estimated_pick_up: "2021-03-30T15:00:00.000Z",
                picked_up_time: null,
                approved: 1,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 1,
                    res_food_name: "Apple",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 3,
                    res_food_name: "Avocado",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 123,
                username: "sean1",
                order_time: "2021-03-28T19:58:11.000Z",
                estimated_pick_up: "2021-04-04T15:00:00.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 3,
                    res_food_name: "Avocado",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 4,
                    res_food_name: "Swiss Cheese",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 125,
                username: "sean1",
                order_time: "2021-03-30T22:36:15.000Z",
                estimated_pick_up: "2021-04-06T15:00:10.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 5,
                    res_food_name: "Cheddar Cheese",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 8,
                    res_food_name: "Pear",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 203,
                username: "sean1",
                order_time: "2021-04-02T01:03:56.000Z",
                estimated_pick_up: "2021-04-08T15:00:00.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 9,
                    res_food_name: "Potato",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 10,
                    res_food_name: "Peanuts",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 12,
                    res_food_name: "Noodle",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 13,
                    res_food_name: "Sparkling Water",
                    res_food_quantity: 1,
                  },
                ],
              },
            ],
            foods: [
              {
                food_id: 1,
                food_name: "Apple",
                qr_code: null,
                quantity: 25,
              },
              {
                food_id: 2,
                food_name: "Orange",
                qr_code: null,
                quantity: 78,
              },
              {
                food_id: 3,
                food_name: "Avocado",
                qr_code: 123123123,
                quantity: 2343,
              },
              {
                food_id: 4,
                food_name: "Swiss Cheese",
                qr_code: 10101011,
                quantity: 22,
              },
              {
                food_id: 5,
                food_name: "Cheddar Cheese",
                qr_code: 1010111011,
                quantity: 2,
              },
              {
                food_id: 8,
                food_name: "Pear",
                qr_code: 2078,
                quantity: 41,
              },
              {
                food_id: 9,
                food_name: "Potato",
                qr_code: 5224,
                quantity: 4112,
              },
              {
                food_id: 10,
                food_name: "Peanuts",
                qr_code: 8630,
                quantity: 121,
              },
              {
                food_id: 11,
                food_name: "Eggs",
                qr_code: 37,
                quantity: 1,
              },
              {
                food_id: 12,
                food_name: "Noodle",
                qr_code: 2850,
                quantity: 5,
              },
              {
                food_id: 13,
                food_name: "Sparkling Water",
                qr_code: 7065,
                quantity: 123,
              },
            ],
            hours: [
              {
                day: 1,
                open: "16:00:00",
                close: "16:30:50",
                detail: "jdshkjfldkffs",
              },
              {
                day: 2,
                open: "09:00:00",
                close: "18:00:00",
                detail: "By Kenny and Kenny Only and k",
              },
              {
                day: 3,
                open: "07:00:00",
                close: "23:00:00",
                detail: "By Ilkyu and Ilkyu Only",
              },
              {
                day: 4,
                open: "10:00:00",
                close: "15:00:00",
                detail: "By Appointment Only",
              },
              {
                day: 5,
                open: "10:00:00",
                close: "15:00:00",
                detail: "By Appointment Only",
              },
              {
                day: 6,
                open: "10:00:00",
                close: "15:00:00",
                detail: "By Appointment Only",
              },
              {
                day: 7,
                open: "10:00:00",
                close: "15:00:00",
                detail: "By Appointment Only",
              },
            ],
          },
          {
            pantry_id: 2,
            name: "Second Harvest Foodbank of Southern Wisconsin",
            address: "2802 Dairy Dr",
            zip: 53718,
            city: "Madison",
            state: "WI",
            phone_number: "6082239121",
            details: "lorem ipsum dolor",
            img_src:
              "https://lh5.googleusercontent.com/p/AF1QipOukd313uIyXDlvMDbvc95D4joVMz-1ywvRnW-P=w408-h271-k-no",
            lat: 43.07,
            lon: -89.41,
            website: "https://www.secondharvestmadison.org/",
            reservations: [
              {
                reservation_id: 108,
                username: "sean1",
                order_time: "2021-03-25T21:52:58.000Z",
                estimated_pick_up: "2021-03-30T15:00:00.000Z",
                picked_up_time: null,
                approved: 1,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 1,
                    res_food_name: "Apple",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 3,
                    res_food_name: "Avocado",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 109,
                username: "sean1",
                order_time: "2021-03-25T21:53:53.000Z",
                estimated_pick_up: "2021-03-30T15:00:00.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: null,
                    res_food_name: null,
                    res_food_quantity: null,
                  },
                ],
              },
              {
                reservation_id: 110,
                username: "sean1",
                order_time: "2021-03-26T10:13:21.000Z",
                estimated_pick_up: "2021-03-30T15:00:00.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 1,
                    res_food_name: "Apple",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 3,
                    res_food_name: "Avocado",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 111,
                username: "sean1",
                order_time: "2021-03-26T10:13:26.000Z",
                estimated_pick_up: "2021-03-30T15:00:00.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: null,
                    res_food_name: null,
                    res_food_quantity: null,
                  },
                ],
              },
              {
                reservation_id: 112,
                username: "sean1",
                order_time: "2021-03-26T07:25:01.000Z",
                estimated_pick_up: "2021-03-30T15:00:00.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: null,
                    res_food_name: null,
                    res_food_quantity: null,
                  },
                ],
              },
              {
                reservation_id: 113,
                username: "sean1",
                order_time: "2021-03-26T07:25:05.000Z",
                estimated_pick_up: "2021-03-30T15:00:00.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 1,
                    res_food_name: "Apple",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                  {
                    res_food_id: 3,
                    res_food_name: "Avocado",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 204,
                username: "sean3",
                order_time: "2021-04-09T05:56:47.000Z",
                estimated_pick_up: "2021-04-09T06:56:47.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 205,
                username: "sean3",
                order_time: "2021-04-10T09:50:22.000Z",
                estimated_pick_up: "2021-04-10T02:50:22.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 206,
                username: "sean3",
                order_time: "2021-04-10T09:51:41.000Z",
                estimated_pick_up: "2021-04-10T02:51:41.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 207,
                username: "sean3",
                order_time: "2021-04-10T09:53:58.000Z",
                estimated_pick_up: "2021-04-10T02:53:58.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 208,
                username: "sean3",
                order_time: "2021-04-10T09:54:55.000Z",
                estimated_pick_up: "2021-04-10T02:54:54.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                ],
              },
              {
                reservation_id: 209,
                username: "sean3",
                order_time: "2021-04-10T09:55:44.000Z",
                estimated_pick_up: "2021-04-10T02:55:44.000Z",
                picked_up_time: null,
                approved: 0,
                cancelled: 0,
                res_foods: [
                  {
                    res_food_id: 2,
                    res_food_name: "Orange",
                    res_food_quantity: 1,
                  },
                ],
              },
            ],
            foods: [
              {
                food_id: 1,
                food_name: "Apple",
                qr_code: null,
                quantity: 7,
              },
              {
                food_id: 2,
                food_name: "Orange",
                qr_code: null,
                quantity: 11,
              },
              {
                food_id: 3,
                food_name: "Avocado",
                qr_code: 123123123,
                quantity: 5,
              },
              {
                food_id: 4,
                food_name: "Swiss Cheese",
                qr_code: 10101011,
                quantity: 199,
              },
            ],
            hours: [
              {
                day: 1,
                open: "01:00:00",
                close: "02:30:00",
                detail: "By Appointment Only",
              },
              {
                day: 2,
                open: "08:30:00",
                close: "16:00:00",
                detail: "Curbside Pickup Only",
              },
              {
                day: 3,
                open: "08:30:00",
                close: "16:00:00",
                detail: "Curbside Pickup Only",
              },
              {
                day: 4,
                open: "08:30:00",
                close: "16:00:00",
                detail: "Curbside Pickup Only",
              },
              {
                day: 5,
                open: "08:30:00",
                close: "17:59:00",
                detail: "",
              },
              {
                day: 6,
                open: "00:00:00",
                close: "00:00:00",
                detail: null,
              },
              {
                day: 7,
                open: "00:00:00",
                close: "00:00:00",
                detail: null,
              },
            ],
          },
        ],
      },
    },
    cart: [
      {
        item: {
          food_id: 2,
          food_name: "Orange",
          qr_code: null,
          quantity: 11,
        },
        cartQuantity: "1",
        pantry: {
          pantry_id: 2,
          name: "Second Harvest Foodbank of Southern Wisconsin",
          address: "2802 Dairy Dr",
          zip: 53718,
          city: "Madison",
          state: "WI",
          phone_number: "6082239121",
          details: "lorem ipsum dolor",
          img_src:
            "https://lh5.googleusercontent.com/p/AF1QipOukd313uIyXDlvMDbvc95D4joVMz-1ywvRnW-P=w408-h271-k-no",
          lat: 43.07,
          lon: -89.41,
          website: "https://www.secondharvestmadison.org/",
          reservations: [
            {
              reservation_id: 108,
              username: "sean1",
              order_time: "2021-03-25T21:52:58.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 1,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 1,
                  res_food_name: "Apple",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 3,
                  res_food_name: "Avocado",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 109,
              username: "sean1",
              order_time: "2021-03-25T21:53:53.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: null,
                  res_food_name: null,
                  res_food_quantity: null,
                },
              ],
            },
            {
              reservation_id: 110,
              username: "sean1",
              order_time: "2021-03-26T10:13:21.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 1,
                  res_food_name: "Apple",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 3,
                  res_food_name: "Avocado",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 111,
              username: "sean1",
              order_time: "2021-03-26T10:13:26.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: null,
                  res_food_name: null,
                  res_food_quantity: null,
                },
              ],
            },
            {
              reservation_id: 112,
              username: "sean1",
              order_time: "2021-03-26T07:25:01.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: null,
                  res_food_name: null,
                  res_food_quantity: null,
                },
              ],
            },
            {
              reservation_id: 113,
              username: "sean1",
              order_time: "2021-03-26T07:25:05.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 1,
                  res_food_name: "Apple",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 3,
                  res_food_name: "Avocado",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 204,
              username: "sean3",
              order_time: "2021-04-09T05:56:47.000Z",
              estimated_pick_up: "2021-04-09T06:56:47.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 205,
              username: "sean3",
              order_time: "2021-04-10T09:50:22.000Z",
              estimated_pick_up: "2021-04-10T02:50:22.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 206,
              username: "sean3",
              order_time: "2021-04-10T09:51:41.000Z",
              estimated_pick_up: "2021-04-10T02:51:41.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 207,
              username: "sean3",
              order_time: "2021-04-10T09:53:58.000Z",
              estimated_pick_up: "2021-04-10T02:53:58.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 208,
              username: "sean3",
              order_time: "2021-04-10T09:54:55.000Z",
              estimated_pick_up: "2021-04-10T02:54:54.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 209,
              username: "sean3",
              order_time: "2021-04-10T09:55:44.000Z",
              estimated_pick_up: "2021-04-10T02:55:44.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
          ],
          foods: [
            {
              food_id: 1,
              food_name: "Apple",
              qr_code: null,
              quantity: 7,
            },
            {
              food_id: 2,
              food_name: "Orange",
              qr_code: null,
              quantity: 11,
            },
            {
              food_id: 3,
              food_name: "Avocado",
              qr_code: 123123123,
              quantity: 5,
            },
            {
              food_id: 4,
              food_name: "Swiss Cheese",
              qr_code: 10101011,
              quantity: 199,
            },
          ],
          hours: [
            {
              day: 1,
              open: "01:00:00",
              close: "02:30:00",
              detail: "By Appointment Only",
            },
            {
              day: 2,
              open: "08:30:00",
              close: "16:00:00",
              detail: "Curbside Pickup Only",
            },
            {
              day: 3,
              open: "08:30:00",
              close: "16:00:00",
              detail: "Curbside Pickup Only",
            },
            {
              day: 4,
              open: "08:30:00",
              close: "16:00:00",
              detail: "Curbside Pickup Only",
            },
            {
              day: 5,
              open: "08:30:00",
              close: "17:59:00",
              detail: "",
            },
            {
              day: 6,
              open: "00:00:00",
              close: "00:00:00",
              detail: null,
            },
            {
              day: 7,
              open: "00:00:00",
              close: "00:00:00",
              detail: null,
            },
          ],
        },
      },
      {
        item: {
          food_id: 3,
          food_name: "Avocado",
          qr_code: 123123123,
          quantity: 5,
        },
        cartQuantity: "2",
        pantry: {
          pantry_id: 2,
          name: "Second Harvest Foodbank of Southern Wisconsin",
          address: "2802 Dairy Dr",
          zip: 53718,
          city: "Madison",
          state: "WI",
          phone_number: "6082239121",
          details: "lorem ipsum dolor",
          img_src:
            "https://lh5.googleusercontent.com/p/AF1QipOukd313uIyXDlvMDbvc95D4joVMz-1ywvRnW-P=w408-h271-k-no",
          lat: 43.07,
          lon: -89.41,
          website: "https://www.secondharvestmadison.org/",
          reservations: [
            {
              reservation_id: 108,
              username: "sean1",
              order_time: "2021-03-25T21:52:58.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 1,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 1,
                  res_food_name: "Apple",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 3,
                  res_food_name: "Avocado",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 109,
              username: "sean1",
              order_time: "2021-03-25T21:53:53.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: null,
                  res_food_name: null,
                  res_food_quantity: null,
                },
              ],
            },
            {
              reservation_id: 110,
              username: "sean1",
              order_time: "2021-03-26T10:13:21.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 1,
                  res_food_name: "Apple",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 3,
                  res_food_name: "Avocado",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 111,
              username: "sean1",
              order_time: "2021-03-26T10:13:26.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: null,
                  res_food_name: null,
                  res_food_quantity: null,
                },
              ],
            },
            {
              reservation_id: 112,
              username: "sean1",
              order_time: "2021-03-26T07:25:01.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: null,
                  res_food_name: null,
                  res_food_quantity: null,
                },
              ],
            },
            {
              reservation_id: 113,
              username: "sean1",
              order_time: "2021-03-26T07:25:05.000Z",
              estimated_pick_up: "2021-03-30T15:00:00.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 1,
                  res_food_name: "Apple",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
                {
                  res_food_id: 3,
                  res_food_name: "Avocado",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 204,
              username: "sean3",
              order_time: "2021-04-09T05:56:47.000Z",
              estimated_pick_up: "2021-04-09T06:56:47.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 205,
              username: "sean3",
              order_time: "2021-04-10T09:50:22.000Z",
              estimated_pick_up: "2021-04-10T02:50:22.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 206,
              username: "sean3",
              order_time: "2021-04-10T09:51:41.000Z",
              estimated_pick_up: "2021-04-10T02:51:41.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 207,
              username: "sean3",
              order_time: "2021-04-10T09:53:58.000Z",
              estimated_pick_up: "2021-04-10T02:53:58.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 208,
              username: "sean3",
              order_time: "2021-04-10T09:54:55.000Z",
              estimated_pick_up: "2021-04-10T02:54:54.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
            {
              reservation_id: 209,
              username: "sean3",
              order_time: "2021-04-10T09:55:44.000Z",
              estimated_pick_up: "2021-04-10T02:55:44.000Z",
              picked_up_time: null,
              approved: 0,
              cancelled: 0,
              res_foods: [
                {
                  res_food_id: 2,
                  res_food_name: "Orange",
                  res_food_quantity: 1,
                },
              ],
            },
          ],
          foods: [
            {
              food_id: 1,
              food_name: "Apple",
              qr_code: null,
              quantity: 7,
            },
            {
              food_id: 2,
              food_name: "Orange",
              qr_code: null,
              quantity: 11,
            },
            {
              food_id: 3,
              food_name: "Avocado",
              qr_code: 123123123,
              quantity: 5,
            },
            {
              food_id: 4,
              food_name: "Swiss Cheese",
              qr_code: 10101011,
              quantity: 199,
            },
          ],
          hours: [
            {
              day: 1,
              open: "01:00:00",
              close: "02:30:00",
              detail: "By Appointment Only",
            },
            {
              day: 2,
              open: "08:30:00",
              close: "16:00:00",
              detail: "Curbside Pickup Only",
            },
            {
              day: 3,
              open: "08:30:00",
              close: "16:00:00",
              detail: "Curbside Pickup Only",
            },
            {
              day: 4,
              open: "08:30:00",
              close: "16:00:00",
              detail: "Curbside Pickup Only",
            },
            {
              day: 5,
              open: "08:30:00",
              close: "17:59:00",
              detail: "",
            },
            {
              day: 6,
              open: "00:00:00",
              close: "00:00:00",
              detail: null,
            },
            {
              day: 7,
              open: "00:00:00",
              close: "00:00:00",
              detail: null,
            },
          ],
        },
      },
    ],
  },
};
