export default {
  foods: [
    {
      id: 1,
      name: "Apple",
      qr_code: null,
      NUTRITION_COLUMNS_PLACEHOLDER: "20 (test_data)",
    },
    {
      id: 2,
      name: "Orange",
      qr_code: null,
      NUTRITION_COLUMNS_PLACEHOLDER: "15 (test_data)",
    },
    {
      id: 3,
      name: "Avocado",
      qr_code: 123123123,
      NUTRITION_COLUMNS_PLACEHOLDER: "12 (test_data)",
    },
    {
      id: 4,
      name: "Swiss Cheese",
      qr_code: 10101011,
      NUTRITION_COLUMNS_PLACEHOLDER: "15 (test_data)",
    },
    {
      id: 5,
      name: "Cheddar Cheese",
      qr_code: 1010111011,
      NUTRITION_COLUMNS_PLACEHOLDER: "14 (test_data)",
    },
    {
      id: 6,
      name: "New Food1",
      qr_code: 2147483647,
      NUTRITION_COLUMNS_PLACEHOLDER: "85 (test_data)",
    },
    {
      id: 7,
      name: "New Food",
      qr_code: 2147483647,
      NUTRITION_COLUMNS_PLACEHOLDER: "54 (test_data)",
    },
    {
      id: 8,
      name: "Pear",
      qr_code: 2078,
      NUTRITION_COLUMNS_PLACEHOLDER: "95 (test_data)",
    },
    {
      id: 9,
      name: "Potato",
      qr_code: 5224,
      NUTRITION_COLUMNS_PLACEHOLDER: "13 (test_data)",
    },
    {
      id: 10,
      name: "Peanuts",
      qr_code: 8630,
      NUTRITION_COLUMNS_PLACEHOLDER: "13 (test_data)",
    },
    {
      id: 11,
      name: "Eggs",
      qr_code: 37,
      NUTRITION_COLUMNS_PLACEHOLDER: "17 (test_data)",
    },
    {
      id: 12,
      name: "Noodle",
      qr_code: 2850,
      NUTRITION_COLUMNS_PLACEHOLDER: "50 (test_data)",
    },
    {
      id: 13,
      name: "Sparkling Water",
      qr_code: 7065,
      NUTRITION_COLUMNS_PLACEHOLDER: "65 (test_data)",
    },
    {
      id: 15,
      name: "New Food",
      qr_code: 2147483647,
      NUTRITION_COLUMNS_PLACEHOLDER: "55 (test_data)",
    },
    {
      id: 16,
      name: "Baguette ",
      qr_code: 1544,
      NUTRITION_COLUMNS_PLACEHOLDER: "12 (test_data)",
    },
    {
      id: 21,
      name: "Broccoli",
      qr_code: null,
      NUTRITION_COLUMNS_PLACEHOLDER: "84 (test_data)",
    },
    {
      id: 22,
      name: "Cheese Sauce",
      qr_code: null,
      NUTRITION_COLUMNS_PLACEHOLDER: "54 (test_data)",
    },
    {
      id: 24,
      name: "Kiwi",
      qr_code: null,
      NUTRITION_COLUMNS_PLACEHOLDER: "84 (test_data)",
    },
    {
      id: 25,
      name: "Avocado",
      qr_code: 8795,
      NUTRITION_COLUMNS_PLACEHOLDER: "654 (test_data)",
    },
  ],
};
