export default {
  pantries: [
    {
      pantry_id: 1,
      name: "The River Food Pantry",
      address: "2201 Darwin Rd",
      zip: 53699,
      city: "Madison",
      state: "WI",
      phone_number: "6084428819",
      details: "Here to serve! - Go Badgers!",
      img_src:
        "https://lh5.googleusercontent.com/p/AF1QipM6UYI64xgIkJx1w_t7RLh8eVCjelB9ogeoW_A3=w426-h240-k-no",
      lat: 43.07,
      lon: -89.4,
      website: "https://www.riverfoodpantry.org/",
      foods: [
        {
          food_id: 1,
          food_name: "Apple",
          qr_code: null,
          quantity: 5,
        },
        {
          food_id: 2,
          food_name: "Orange",
          qr_code: null,
          quantity: 710,
        },
        {
          food_id: 3,
          food_name: "Avocado",
          qr_code: 123123123,
          quantity: -4,
        },
        {
          food_id: 4,
          food_name: "Swiss Cheese",
          qr_code: 10101011,
          quantity: 260,
        },
        {
          food_id: 5,
          food_name: "Cheddar Cheese",
          qr_code: 1010111011,
          quantity: 244,
        },
        {
          food_id: 8,
          food_name: "Pear",
          qr_code: 2078,
          quantity: 867,
        },
        {
          food_id: 9,
          food_name: "Potato",
          qr_code: 5224,
          quantity: 4118,
        },
        {
          food_id: 10,
          food_name: "Peanuts",
          qr_code: 8630,
          quantity: 184,
        },
        {
          food_id: 11,
          food_name: "Eggs",
          qr_code: 37,
          quantity: 1215,
        },
        {
          food_id: 12,
          food_name: "Noodle",
          qr_code: 2850,
          quantity: 513127,
        },
        {
          food_id: 13,
          food_name: "Sparkling Water",
          qr_code: 7065,
          quantity: 120,
        },
        {
          food_id: 16,
          food_name: "Baguette ",
          qr_code: 1544,
          quantity: 15,
        },
        {
          food_id: 21,
          food_name: "Broccoli",
          qr_code: null,
          quantity: 21,
        },
        {
          food_id: 22,
          food_name: "Cheese Sauce",
          qr_code: null,
          quantity: 26,
        },
        {
          food_id: 24,
          food_name: "Kiwi",
          qr_code: null,
          quantity: 543,
        },
        {
          food_id: 25,
          food_name: "Avocado",
          qr_code: 8795,
          quantity: 0,
        },
      ],
      hours: [
        {
          day: 1,
          open: "07:50:00",
          close: "20:30:00",
          detail: "go Scavenge!\ngo Team!",
        },
        {
          day: 2,
          open: "06:00:00",
          close: "19:00:00",
          detail: "By Kenny and Kenny Only and k",
        },
        {
          day: 3,
          open: "07:00:00",
          close: "23:00:00",
          detail: "By Ilkyu and Ilkyu Only and Ilkyu and LQ and ",
        },
        {
          day: 4,
          open: "10:00:00",
          close: "11:55:00",
          detail: "By Appointment Only",
        },
        {
          day: 5,
          open: "00:00:00",
          close: "00:00:00",
          detail: "By Appointment Only",
        },
        {
          day: 6,
          open: "10:30:00",
          close: "15:30:00",
          detail: "By Appointment Only",
        },
        {
          day: 7,
          open: "10:00:00",
          close: "15:00:00",
          detail: "By Appointment Only",
        },
      ],
    },
    {
      pantry_id: 2,
      name: "Second Harvest Foodbank of Southern Wisconsin",
      address: "2802 Dairy Dr",
      zip: 53718,
      city: "Madison",
      state: "WI",
      phone_number: "6082239121",
      details: "lorem ipsum dolor",
      img_src:
        "https://lh5.googleusercontent.com/p/AF1QipOukd313uIyXDlvMDbvc95D4joVMz-1ywvRnW-P=w408-h271-k-no",
      lat: 43.07,
      lon: -89.41,
      website: "https://www.secondharvestmadison.org/",
      foods: [
        {
          food_id: 1,
          food_name: "Apple",
          qr_code: null,
          quantity: 9,
        },
        {
          food_id: 2,
          food_name: "Orange",
          qr_code: null,
          quantity: 7,
        },
        {
          food_id: 3,
          food_name: "Avocado",
          qr_code: 123123123,
          quantity: -1,
        },
        {
          food_id: 4,
          food_name: "Swiss Cheese",
          qr_code: 10101011,
          quantity: 193,
        },
      ],
      hours: [
        {
          day: 1,
          open: "01:00:00",
          close: "02:30:00",
          detail: "By Appointment Only",
        },
        {
          day: 2,
          open: "08:30:00",
          close: "16:00:00",
          detail: "Curbside Pickup Only",
        },
        {
          day: 3,
          open: "08:30:00",
          close: "16:00:00",
          detail: "Curbside Pickup Only",
        },
        {
          day: 4,
          open: "08:30:00",
          close: "16:00:00",
          detail: "Curbside Pickup Only",
        },
        {
          day: 5,
          open: "08:30:00",
          close: "17:59:00",
          detail: "",
        },
        {
          day: 6,
          open: "00:00:00",
          close: "00:00:00",
          detail: null,
        },
        {
          day: 7,
          open: "00:00:00",
          close: "00:00:00",
          detail: null,
        },
      ],
    },
  ],
};
