# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Jest coverage report

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v1.1
        working-directory: frontend
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_script: npm run test -- --coverage --watchAll=false
          threshold: 80 # we aim for 80% coverage
