name: Frontend Coverage Report

on:
  pull_request:
    branches:
      - "**"

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test -- --coverage --watchAll=false
      - uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./frontend/coverage/lcov.info
      - uses: ArtiomTr/jest-coverage-report-action@v1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80 # we aim for 80% coverage
