# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Jest Coverage Report

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - uses: ziishaned/jest-reporter-action@0.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
