# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Jest Coverage Report

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: mattallty/jest-github-action@v1.0.3
        with:
          # The test command to run
          # test-command: npm run test -- --coverage --watchAll=false
          # Subdirectory to run tests in
          working-directory: "frontend"
